## Imports

In [59]:
from numpy.random import seed
seed(888)

import tensorflow.compat.v1 as tf

tf.disable_v2_behavior() 

tf.set_random_seed(404)

In [60]:
import os
import numpy as np

from time import strftime
from PIL import Image

## Constants

In [61]:
X_TRAIN_PATH = 'MNIST/digit_xtrain.csv'
X_TEST_PATH = 'MNIST/digit_xtest.csv'
Y_TRAIN_PATH = 'MNIST/digit_ytrain.csv'
Y_TEST_PATH = 'MNIST/digit_ytest.csv'

LOGGING_PATH = 'tensorboard_mnist_digit_logs/'

NR_CLASSES = 10
VALIDATION_SIZE = 10000
IMAGE_WIDTH = 28
IMAGE_HEIGHT = 28
CHANNELS = 1
TOTAL_INPUTS = IMAGE_WIDTH*IMAGE_HEIGHT*CHANNELS

## Get the Data

In [62]:
%%time
# Load Labels 
y_train_all = np.loadtxt(Y_TRAIN_PATH, delimiter=',', dtype=int)

CPU times: total: 516 ms
Wall time: 777 ms


In [63]:
# Load Testing Labels
y_train_all.shape

(60000,)

In [64]:
y_test = np.loadtxt(Y_TEST_PATH, delimiter=',', dtype=int)

In [65]:
%%time
# Load Training Features
x_train_all = np.loadtxt(X_TRAIN_PATH, delimiter=',', dtype=int)

CPU times: total: 48 s
Wall time: 51.7 s


In [66]:
%%time
# Load Testing Features
x_test = np.loadtxt(X_TEST_PATH, delimiter=',', dtype=int)

CPU times: total: 7.8 s
Wall time: 8.48 s


## Explore

In [67]:
# 60.000 Train Data, 28 x 28 x 1 = 784 
x_train_all.shape

(60000, 784)

In [68]:
# Each example is an array of 784 int values 0 - 255
print(x_train_all[0].shape)
x_train_all[0]

(784,)


array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   3,  18,  18,  18,
       126, 136, 175,  26, 166, 255, 247, 127,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,  30,  36,  94, 154, 17

In [69]:
# 60.000 Train Labels
y_train_all.shape

(60000,)

In [70]:
# Labels of Digits from 0 to 9
y_train_all

array([5, 0, 4, ..., 5, 6, 8])

In [71]:
# 10.000 Testing Data
x_test.shape

(10000, 784)

In [72]:
x_test

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [73]:
# 10.000 Testing Labels
y_test.shape

(10000,)

In [74]:
y_test

array([7, 2, 1, ..., 4, 5, 6])

## Data Preprocessing

In [75]:
# Re-scale Features
x_train_all, x_test = x_train_all / 255.0, x_test / 255.0

## Convert target values to one-hot encoding

In [76]:
values = y_train_all[:5]
np.eye(10)[values]

array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [77]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [78]:
np.eye(10)[2]

array([0., 0., 1., 0., 0., 0., 0., 0., 0., 0.])

In [79]:
values

array([5, 0, 4, 1, 9])

In [80]:
values[4]

9

In [81]:
# Convert y_train_all to One Hot Encoding
y_train_all = np.eye(NR_CLASSES)[y_train_all]

In [82]:
y_train_all.shape

(60000, 10)

In [83]:
y_train_all

array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.]])

In [84]:
y_test = np.eye(NR_CLASSES)[y_test]
y_test.shape

(10000, 10)

## Create validation dataset from training data

In [85]:
# Create x, y Validation Sets of 10.000 data
x_val = x_train_all[:VALIDATION_SIZE]
y_val = y_train_all[:VALIDATION_SIZE]

In [86]:
print(x_val.shape)
print(y_val.shape)

(10000, 784)
(10000, 10)


In [87]:
# Update x, y Training Sets
x_train = x_train_all[VALIDATION_SIZE:]
y_train = y_train_all[VALIDATION_SIZE:]

In [88]:
print(x_train.shape)
print(y_train.shape)

(50000, 784)
(50000, 10)


## Setup Tensorflow Graph

In [145]:
# Placeholder for Features, Raw Inputs
X = tf.placeholder(tf.float32, shape=[None, TOTAL_INPUTS], name='X')
# Placeholder for Labels
Y = tf.placeholder(tf.float32, shape=[None, NR_CLASSES], name='labels')

## Neural Network Architecture

### Hyperparameters

In [146]:
nr_epochs = 50
#learning_rate = 1e-4
learning_rate = 1e-3

# 1st Hidden Layer Neurons
n_hidden1 = 512
# 2nd Hidden Layer Neurons
n_hidden2 = 64

In [147]:
def setup_layer(input, weight_dim, bias_dim, name):
    
    with tf.name_scope(name):
        # Create Weights for Layer (shape: inputs X neurons) using Truncated Normal Distribution
        initial_w = tf.truncated_normal(shape=weight_dim, stddev=0.1, seed=42)
        # Create Tensorfloat Variable holding all Weights of Layer
        w = tf.Variable(initial_value=initial_w, name='W')
        
        # Initialise Biases of Layer - All Start with Same Value 0.0
        initial_b = tf.constant(value=0.0, shape=bias_dim)
        b = tf.Variable(initial_value=initial_b, name='B')
        
        # Store Inputs Coming to Layer
        layer_in = tf.matmul(input, w) + b
        
        if name=='out':
            # Softmax Activation Function for Output Layer
            layer_out = tf.nn.softmax(layer_in)
        else:
            # Relu for Other Layers
            layer_out = tf.nn.relu(layer_in)
        
        tf.summary.histogram('weights', w)
        tf.summary.histogram('biases', b)
        
        return layer_out

In [148]:
# Model Without Dropout
# layer_1 = setup_layer(X, weight_dim=[TOTAL_INPUTS, n_hidden1], 
#                        bias_dim=[n_hidden1], name='layer_1')

# layer_2 = setup_layer(layer_1, weight_dim=[n_hidden1, n_hidden2], 
#                        bias_dim=[n_hidden2], name='layer_2')

# output = setup_layer(layer_2, weight_dim=[n_hidden2, NR_CLASSES], 
#                        bias_dim=[NR_CLASSES], name='out')

# model_name = f'{n_hidden1}-{n_hidden2} LR{learning_rate} E{nr_epochs}'

In [149]:
# Model Wth Dropout
layer_1 = setup_layer(X, weight_dim=[TOTAL_INPUTS, n_hidden1], 
                       bias_dim=[n_hidden1], name='layer_1')

layer_drop = tf.nn.dropout(layer_1, keep_prob=0.8, name='dropout_layer')

layer_2 = setup_layer(layer_drop, weight_dim=[n_hidden1, n_hidden2], 
                       bias_dim=[n_hidden2], name='layer_2')

output = setup_layer(layer_2, weight_dim=[n_hidden2, NR_CLASSES], 
                       bias_dim=[NR_CLASSES], name='out')

model_name = f'{n_hidden1}-DO-{n_hidden2} LR{learning_rate} E{nr_epochs}'

Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.


## Tensorboard Setup

In [150]:
# Folder for Tensorboard
folder_name = f'{model_name} at {strftime("%H %M")}'
directory = os.path.join(LOGGING_PATH, folder_name)

try:
    os.makedirs(directory)
except OSError as exception:
    print(exception.strerror)
else:
    print('Successfully created directories!')

Successfully created directories!


## Loss, Optimisation & Metrics

### Defining Loss Function

In [151]:
with tf.name_scope('loss_calc'):
    # Logits: Outputs from Output Layer
    # Use the Avg due to Batchess
    loss = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(labels=Y, logits=output))

### Defining Optimizer

In [152]:
# Adam Optimiser
with tf.name_scope('optimizer'):
    # Use my Learning Rate
    optimizer = tf.train.AdamOptimizer(learning_rate)
    # Minimise Loss Calcuated from Cross Enotropy 
    train_step = optimizer.minimize(loss)

### Accuracy Metric

In [153]:
with tf.name_scope('accuracy_calc'):
    # Compare Prediction & True Label
    # Use Index of Largest Probability for the Output
    correct_pred = tf.equal(tf.argmax(output, axis=1), tf.argmax(Y, axis=1))
    # Accuracy: the Avg of all Batches
    accuracy = tf.reduce_mean(tf.cast(correct_pred, tf.float32))

In [154]:
with tf.name_scope('performance'):
    tf.summary.scalar('accuracy', accuracy)
    tf.summary.scalar('cost', loss)

### Check Input Images in Tensorboard

In [155]:
with tf.name_scope('show_image'):
    # Image Date are in Single Row of 784 Values - Reshape them to: 28 x 28 x 1
    x_image = tf.reshape(X, [-1, 28, 28, 1])
    # Show 4 Images
    tf.summary.image('image_input', x_image, max_outputs=4)

## Run Session - Tensorflow

In [156]:
sess = tf.Session()

### Setup Filewriter and Merge Summaries

In [157]:
# Include all Summuries of TensorFlow
merged_summary = tf.summary.merge_all()

train_writer = tf.summary.FileWriter(directory + '/train')
train_writer.add_graph(sess.graph)

validation_writer = tf.summary.FileWriter(directory + '/validation')

### Initialise all the variables

In [158]:
init = tf.global_variables_initializer()
sess.run(init)

### Batching the Data

In [159]:
size_of_batch = 1000

In [160]:
num_examples = y_train.shape[0]
nr_iterations = int(num_examples/size_of_batch)

# Help Keep Track when 1 Bath Ends and Next Starts
# 1st Batch: 0 to 999, 2nd Batch: 1000 - 1999 etc
index_in_epoch = 0

In [161]:
# Going from One Batch to Next
# data: features X, labels: Y
def next_batch(batch_size, data, labels):
    
    global num_examples
    global index_in_epoch
    
    start = index_in_epoch
    index_in_epoch += batch_size
    
    # Start Next Epoch
    if index_in_epoch > num_examples:
        start = 0
        index_in_epoch = batch_size
    
    # End of Bact
    end = index_in_epoch
    
    return data[start:end], labels[start:end]

### Training Loop

In [162]:
# Run Through All Epochs
for epoch in range(nr_epochs):
    
    # ============= Training Dataset =========
    # Iterate Through Data
    for i in range(nr_iterations):
        
        batch_x, batch_y = next_batch(batch_size=size_of_batch, data=x_train, labels=y_train)
        # Create Dictionary to Feed it to TensorFlow Session
        feed_dictionary = {X:batch_x, Y:batch_y}
        # Session Runs All Calculations - Training Step
        sess.run(train_step, feed_dict=feed_dictionary)
        
    # Accuracy Calculated on Batct - feed dictionary
    s, batch_accuracy = sess.run(fetches=[merged_summary, accuracy], feed_dict=feed_dictionary)
        
    train_writer.add_summary(s, epoch)
    
    print(f'Epoch {epoch} \t| Training Accuracy = {batch_accuracy}')
    
    # ================== Validation ======================
    # Not in Batches
    summary = sess.run(fetches=merged_summary, feed_dict={X:x_val, Y:y_val})
    validation_writer.add_summary(summary, epoch)

print('Done training!')

Epoch 0 	| Training Accuracy = 0.8460000157356262
Epoch 1 	| Training Accuracy = 0.859000027179718
Epoch 2 	| Training Accuracy = 0.8610000014305115
Epoch 3 	| Training Accuracy = 0.8679999709129333
Epoch 4 	| Training Accuracy = 0.8690000176429749
Epoch 5 	| Training Accuracy = 0.9660000205039978
Epoch 6 	| Training Accuracy = 0.9739999771118164
Epoch 7 	| Training Accuracy = 0.9810000061988831
Epoch 8 	| Training Accuracy = 0.9789999723434448
Epoch 9 	| Training Accuracy = 0.9829999804496765
Epoch 10 	| Training Accuracy = 0.9890000224113464
Epoch 11 	| Training Accuracy = 0.9879999756813049
Epoch 12 	| Training Accuracy = 0.9890000224113464
Epoch 13 	| Training Accuracy = 0.9860000014305115
Epoch 14 	| Training Accuracy = 0.9900000095367432
Epoch 15 	| Training Accuracy = 0.9919999837875366
Epoch 16 	| Training Accuracy = 0.9890000224113464
Epoch 17 	| Training Accuracy = 0.9860000014305115
Epoch 18 	| Training Accuracy = 0.9900000095367432
Epoch 19 	| Training Accuracy = 0.99299997

# Make a Prediction

In [163]:
img = Image.open('MNIST/test_img.png')
img

In [164]:
bw = img.convert('L')

In [165]:
img_array = np.invert(bw)

In [166]:
img_array.shape

(28, 28)

In [167]:
test_img = img_array.ravel()

In [168]:
test_img.shape

(784,)

In [169]:
prediction = sess.run(fetches=tf.argmax(output, axis=1), feed_dict={X:[test_img]})

In [170]:
print(f'Prediction for test image is {prediction}')

Prediction for test image is [2]


# Testing and Evaluation

In [171]:
test_accuracy = sess.run(fetches=accuracy, feed_dict={X:x_test, Y:y_test})
print(f'Accuracy on test set is {test_accuracy:0.2%}')

Accuracy on test set is 97.93%


# Reset for the Next Run

In [172]:
# Release Resources for Train Data
train_writer.close()
# Release Resources for Validation Data
validation_writer.close()
sess.close()
tf.reset_default_graph()